version: 3;
services:
  proxy:
    container_name: proxy
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - "8000:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/nginx.conf
      - ./app/:/usr/share/nginx/html
  db:
    image: mysql:8.2
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
  adminer:
    image: adminer
    ports:
      - "8080:8080"
